### ISSUE TITLE
US02 - Interface Cash In - Integração

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#110]
## Descrição da Mudança *

Eu, como usuário desejo inserir recurso na minha conta, no modelo pré-pago, para que eu possa simular a utilização do serviço de cheque especial.

Esta issue destina-se ao desenvolvimento frontend da US02 , referente às requisições ao backend.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Fazer requisição POST ao backend inserindo novo registro à tabela Transaction, fornecendo os dados: type(in), description (boleto ou transferência) e value(valor fornecido pelo usuário)
- [x] Atualizar os saldos em todas as telas.
- [x] Redirecionar o usuário para tela principal após a inserção com sucesso

## Critérios de Aceitação * 

- [x] Criar transação do tipo cash in na tabela de transações quando o usuário fornecer o valor,  o modo de inserção e clicar em "Enviar" e redirecioná-lo à página de acompanhamento de dívida.
- [x] O saldo de todas as páginas deve ser atualizado com a nova inserção.
- [x] Caso o usuário esteja em situação de dívida por cheque especial dentro do prazo de 26 dias valor inserido deve ser abatido na dívida.
- [x] Caso o usuário esteja em cheque especial mas já tenha parcelado a dívida, não deve fazer nada.

**Comment by LuizaCezario** [comment]
A terceira tarefa da issue é redirecionar o usuário para tela de acompanhamento de limite após a inserção com sucesso, mas nesse caso não faria mais sentido redirecionar para a tela principal ou pra uma página de saldo? Já que se trata de uma transação de cash in.

**Comment by mlfaa** [comment]
Sim! Está certo o seu raciocínio, ele deve ser redirecionado para a tela principal onde é mostrado o saldo do usuário.
