### ISSUE TITLE
US01 - Interface Cash Out - Design

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#111]
## Descrição da Mudança *

Eu, como usuário desejo remover recursos na minha conta por meio de compras com crédito,  para que eu possa simular a utilização do serviço de cheque especial.

Esta issue destina-se à produção e planejamento do design da página de realização do CashOut.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x]  Fazer o protótipo de alta fidelidade da tela de Cash Out
- [ ] Implementar design feito

## Critérios de Aceitação * 

- [x] A tela de Cash Out deve conter um campo para fornecer o valor a ser transferido.
- [x] A tela deve conter um campo de descrição da transação com uma lista de opções (compra com cartão, pagamento de boleto, transferência)
- [x] Deve existir um botão "Retirar"

**Comment by mlfaa** [comment]
Prótipo no github pages https://fga-eps-mds.github.io/2019.2-Over26/#/prototype

**Comment by andrewlucasgs** [comment]
Design adicionado a devel.
