### ISSUE TITLE
US01 - Interface Cash Out - Integração 

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#112]
## Descrição da Mudança *

Eu, como usuário desejo remover recursos na minha conta por meio de compras com crédito,  para que eu possa simular a utilização do serviço de cheque especial.

Esta issue destina-se ao desenvolvimento frontend da US01 , referente às requisições ao backend.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Fazer requisição POST ao backend inserindo novo registro à tabela Transaction, fornecendo os dados:  type(out), description (compra com cartão, boleto ou transferência) e value(valor fornecido pelo usuário)
- [x] Caso a transação for uma COMPRA COM CARTÃO, o usuário tenha o serviço ativo mas não tem nenhuma dívida por overdraft dentro do período dos 26 dias e queira usar um recurso maior do que tem no saldo: Fazer requisição UPDATE para overdraft atualizando o atributo limitUsed aumentando-o  e  setando o atributo firstUseDate com a data atual; (Primeiro uso do overdraft)
- [x] Caso a transação for uma COMPRA COM CARTÃO, o usuário já tenha uma dívida por overdraft dentro do período dos 26 dias, mas queira ainda assim comprar: Fazer requisição UPDATE para overdraft atualizando o atributo limitUsed aumentando-o, não alterar atributo firstUseDate (overdraft com outro uso tendo sido feito anteriormente)
- [x] Caso o usuário tenha saldo insuficiente, não tenha o serviço de overdraft ativo e tente fazer qualquer tipo de Cash Out não deve ser realizada nenhuma transação e uma mensagem "Retirada negada" deve aparecer na tela. (Não tem serviço ativo mas quer usar o crédito)
- [x] Redirecionar o usuário para tela de acompanhamento de limite após a remoção com sucesso

## Critérios de Aceitação * 

- [x] Criar transação do tipo cash out caso a transação seja efetuada, na tabela de transações quando o usuário fornecer o valor ,clicar em "Retirar" e redirecioná-lo à página de acompanhamento de dívida.
- [ ] O saldo de todas as páginas deve ser atualizados com a nova remoção.
- [x] Caso o usuário esteja em situação de dívida por cheque especial dentro do prazo de 26 dias deve se  somar o valor retirado à dívida e data de criação da dívida deve continuar a mesma.
- [x] Caso o usuário esteja em cheque especial mas já tenha parcelado a dívida, deve-se setar uma nova data (firstUseDate)
- [x] Caso usuário não tenha serviço ativado, tenha saldo insuficiente e queira realizar retirada, o pedido deve ser negado e o usuário deve ver uma mensagem com essa informação.

 via CRÉDITO*

**Comment by ErickCReis** [comment]
Observações sobre a issue estão no PR #136 .
