### ISSUE TITLE
US21 - Iniciar Aplicação - Backend

### ISSUE THREAD

**Issue by nahmrodrigues** [fga-eps-mds/2019.2-Over26#113]
## Descrição da Mudança *

Eu, como usuário, desejo iniciar a aplicação para que seja possível simular transações e movimentações financeiras.

Esta issue é voltada para fazer controller de inicialização da aplicação para criar usuário e conta.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [ ] Criar controller de inicialização da aplicação, que receberá o nome do usuário como parâmetro e salvará no banco o usuário e a conta (com os outros valores das classes setados de forma fixa)
- [ ] Disponibilizar rota para o front

## Critérios de Aceitação * 

- [ ] A rota deve estar disponível para ser utilizada
- [ ] Devem ser feitos testes unitários para o(s) método(s) criado(s).

**Comment by mlfaa** [comment]
Deve consertar a controller para que funcione perfeitamente, pois está criando mais de um user. Devido a esse fato, ficou de dívida técnica.

**Comment by andrewlucasgs** [comment]
PR aceito, as mudanças solicitadas foram feitas
