### ISSUE TITLE
TS09 - Refatorar Confirmação de Parcelamento

### ISSUE THREAD

**Issue by nahmrodrigues** [fga-eps-mds/2019.2-Over26#114]
## Descrição da Mudança *

Ajustar os atributos "isActive" e "isBlocked" no front e no back para ser possível percorrer todo o fluxo da aplicação.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Ajustar controllers no back, corrigindo a utilização dos atributos.
- [x] Corrigir activities no front para reconhecer os atributos
- [x] Verificar e ajustar classe de requisições no front.

## Critérios de Aceitação * 

- [x] Deve ser diferenciado no front quando o cheque especial está bloqueado  e ativo
- [x] O fluxo de parcelamento esteja funcionando deve estar funcionando conforme a situação do cheque especial (ativo ou bloqueado)

**Comment by mlfaa** [comment]
https://github.com/fga-eps-mds/2019.2-Over26/pull/124

**Comment by mlfaa** [comment]
https://github.com/fga-eps-mds/2019.2-Over26-Backend/pull/19
