### ISSUE TITLE
D05 - Fazer Protótipos de Baixa Fidelidade

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#12]
## Objetivo

Prototipar as principais funcionalidades do sistema.

## Critérios de Aceitação

- [ ]  Protótipo de baixa fidelidade da ideia
- [ ]  Teste com 5 usuários e/ou apresentação para cliente

**Comment by mlfaa** [comment]
Esta issue não será mais necessária no projeto, devido a ideia do projeto já estar bem consolidada, pois já existente no aplicativo da N26 na Europa. É necessário testar o design final com usuários, sendo mais adequado um protótipo de média ou alta fidelidade.

**Comment by mlfaa** [comment]
Esta issue será reaberta, devido a inserção de uma nova funcionalidade no sistema. Há a necessidade de realizar o protótipo de baixa fidelidade, a fim de facilitar o entendimento do fluxo da aplicação com a nova funcionalidade.

**Comment by mlfaa** [comment]
Foi realizado o protótipo de baixa fidelidade no dia 19/09/2019.
![prototipo_baixa_fidelidade](https://user-images.githubusercontent.com/26935097/65651285-61ed7400-dfe4-11e9-9276-142b8bc6e9ab.png)
