### ISSUE TITLE
Estudar Notificações Kotlin

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#123]
## Descrição da Mudança *

É necessário o conhecimento sobre como realizar notificações em Kotlin pela equipe de desenvolvimento. 

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Estudar como realizar notificações em Kotlin
- [x] Realizar um exemplo de uma notificação na aplicação

## Critérios de Aceitação * 

- [x] Transmissão do conhecimento obtido para a equipe de desenvolvimento
- [x] Mostrar o exemplo de notificação feito pela equipe

**Comment by ErickCReis** [comment]
Documentação oficial: [https://developer.android.com/guide/topics/ui/notifiers/notifications](url)

**Comment by ErickCReis** [comment]
Exemplos testados:

- [Notificação simples](https://www.treinaweb.com.br/blog/implementando-uma-notificacao-simples-no-android/): Envia em notificação ao chamar a função `criarNotificacaoSimples()`

- [Notificação programada](https://gist.github.com/BrandonSmith/6679223): Envia uma notificação após x milissegundos depois de chamar a função `scheduleNotification(notification, x)`

**Comment by mlfaa** [comment]
Excelente @ErickCReis e @LuizaCezario !
