### ISSUE TITLE
US08 - Acompanhar período de insenção de juros - Design 

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#126]
## Descrição da Mudança *

Eu, como usuário desejo acompanhar o período de isenção da taxa de juros sob a dívida proveniente do cheque especial, para que eu possa programar o pagamento da mesma.

Esta issue destina-se apenas à consolidação visual do modo como o serviço de acompanhamento do período de isenção vai ser exposto ao usuário. Por tanto, compreende apenas o Design e implementação do layout da página. 

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [ ] Prototipar modo como a informação sobre a isenção será exposta para o usuário 
- [ ] Implementar o layout prototipado

## Critérios de Aceitação * 

- [ ] Protótipo disponível  no Ghpages
- [ ] Layout semelhante à aplicação original do N26 no exterior.

**Comment by mlfaa** [comment]
Issue cancelada, pela falta de necessidade em prototipar a funcionalidade. Foi decidido na reunião em comum acordo com a equipe que faríamos um dropdown com funcionalidades alheias ao funcionamento do fluxo.
