### ISSUE TITLE
US08 - Acompanhar período de insenção de juros - Backend

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#128]
## Descrição da Mudança *

Eu, como usuário desejo acompanhar o período de isenção da taxa de juros sob a dívida proveniente do cheque especial, para que eu possa programar o pagamento da mesma.

Esta issue refere-se à criação da rotina de checagem automática dos 26 dias de isenção da taxa de juros, podendo ser randômica.
 
## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Criar um método para atualizar a data de firstUserDate (-27 dias)
- [x] Criar a dívida (OverdraftDebt)
- [x] Verificar se o Overdrat festá ativo e utilizado
- [x] Testes unitários

## Critérios de Aceitação * 

- [x] Adiantar os 26 dias 
- [x] Criar a dívida após chamar o método
- [x] Se o Overdraft está ativo e utilizado cria a dívida, caso não, não acontece nada 
- [x] Devem ser desenvolvidos testes para o método criado de 70% de cobertura

**Comment by andrewlucasgs** [comment]
Pr mergado com sucesso!
