### ISSUE TITLE
US14 - Acompanhar dívida - Integração

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#138]
## Descrição da Mudança *

Eu, como usuário desejo acompanhar o valor da minha dívida, para que eu possa controlar os meus gastos.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Fazer a requisição obtendo as parcelas da dívida
- [x] Tratar a lista de objetos das parcelas 

## Critérios de Aceitação * 

- [x] O botão de visualizar parcelas da dívida só deve aparecer na tela de acompanhar limite de crédito se o período de isenção de taxas do overdraft tiver passado (acima de 26 dias) e se o usuário já parcelou a dívida
- [x]  Todas as parcelas devem ser apresentadas ao usuário
- [x] As parcelas apresentadas devem estar exibindo as informações referentes a ela (mês da parcela, dia do vencimento e valor)

**Comment by andrewlucasgs** [comment]
PR aceito, mas será necessário revisar o design da tela de track limit, pois está muito sobrecarregada.
