### ISSUE TITLE
US23 - Listar Dívidas - Design

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#150]
## Descrição da Mudança *

Eu, como usuário, desejo visualizar todas as minhas dívidas, anteriores e novas, a fim de acompanhar meu uso do serviço de cheque especial.

Issue destinada à criação e implementação do design da tela de apresentação das dívidas.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] A lista das dívidas com: Número da dívida, número de parcelas, valor total da dívida, dia de vencimento da parcela
- [x] Botão de "Ver dívidas" em TrackLimit

## Critérios de Aceitação * 

- [x] A tela deve seguir os princípios do aplicativo original da N26
- [x] A tela deve ser clean e apresentar as informações de maneira clara
- [x] O protótipo deve estar disponível no GH Pages

**Comment by ErickCReis** [comment]
Os critérios de aceitação foram cumpridos, mas o [PR](https://github.com/fga-eps-mds/2019.2-Over26/pull/159) conta com algumas observações.
