### ISSUE TITLE
US23 - Listar dívidas - Integração

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#151]
## Descrição da Mudança *

Eu, como usuário, desejo visualizar todas as minhas dívidas, anteriores e novas, a fim de acompanhar meu uso do serviço de cheque especial.

Realizar a integração entre o frontend e o backend da aplicação para a apresentação das dívidas.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Integrar o componente que chama a página de apresentação de dívidas com o método desenvolvido no backend da aplicação.
- [x] Listar todas as dívidas do usuário (inclusive a dívida que ainda não foi parcelada)
- [x] Ao clicar na dívida, deve ir para a tela de parcelas da dívida

## Critérios de Aceitação * 

- [x] Ao clicar no menu "dívidas" a página de dívidas deverá ser apresentada

**Comment by BielLopes2000** [comment]
O PR foi aceito, já que está de acordo com os critérios de aceitação.
