### ISSUE TITLE
TS10 - Testes de Aceitação do Frontend

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#153]
## Descrição da Mudança *

Realizar testes de aceitação no frontend.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Testar elegibilidade
- [x] Testar ativar cheque especial
- [x] Testar modificar limite de crédito e salvar

## Critérios de Aceitação * 

- [x] Testar telas do fluxo de contratação do crédito especial
- [x] Testar telas do fluxo de acompanhamento do limite de crédito especial

**Comment by ErickCReis** [comment]
Issue concluida com o PR #160
