### ISSUE TITLE
TS12 - Cancelar Overdraft

### ISSUE THREAD

**Issue by ErickCReis** [fga-eps-mds/2019.2-Over26#156]
## Resultado Esperado

As pressionar o botão `Cancelar Overdraft` não deve ser possível retornar a tela `TrackLimit` até que o usuário volte a reativá-lo.

## Passos para reproduzir (para _bugs_)

1. Iniciar aplicação
2. Ativar cheque especial
3. Acessar cheque especial
4. Cancelar overdraft
5. Acessar cheque especial

### Bug
![image](https://user-images.githubusercontent.com/30873873/68078905-bbed1080-fdbe-11e9-8ec6-387b8e618e40.png)

**Comment by andrewlucasgs** [comment]
PRs aceitos , o bug foi resolvido, portanto a essa issue será fechada.
