### ISSUE TITLE
TS11 - Refatorar controller das transactions - Backend

### ISSUE THREAD

**Issue by nahmrodrigues** [fga-eps-mds/2019.2-Over26#158]
## Descrição da Mudança *

O método de cash-out não está funcionando da maneira como deveria. Quando se usa o limite do cheque especial, o atributo "limite utilizado" do mesmo deve ser igual (em módulo), ao saldo da conta. No entanto, o valor do atributo está sendo setado de maneira equivocada.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Refatorar método de cash-out
- [x] Verificar o comportamento da controller e garantir que tudo está funcionando corretamente
- [x] Refatorar o que for necessário

## Critérios de Aceitação * 

- [x] A controller deve estar funcionando de maneira correta
- [x] Os testes devem estar passando e com cobertura de, no mínimo, 70%

**Comment by isabellacgmsa** [comment]
Durante a realização da tarefa da issue foi encontrado um bug na atualização do saldo da conta e já está sendo consertado.

**Comment by andrewlucasgs** [comment]
PR aceito, bug corrigidos e essa versão já disponivel no staging. Bom trabalho! :+1:
