### ISSUE TITLE
 Consertar controller checkAmount - Back

### ISSUE THREAD

**Issue by JongaMatos** [fga-eps-mds/2019.2-Over26#161]
## Descrição da Mudança *

Foi percebido um bug na branch de desenvolvimento ,mais especificamente na controller checkAmount.
Esse bug afeta a issue https://github.com/fga-eps-mds/2019.2-Over26/issues/151 e esta issue se trata da solução deste bug.

## Tarefas *

- [ ] Alterar a controller checkAmount para retornar o valor correto quando a divida já tiver sido parcelada.

## Critérios de Aceitação * 

- [ ] A controller deve calcular e retornar o valor da divida com juros caso ela não esteja parcelada.
- [ ] A controller deve retornar o valor definido para a divida quando a mesma foi parcelada.

## Resultado Esperado (para _bugs_)

Quando houver uma divida parcelada,ao usar a controller checkAmount,será recalculado o valor da divida ao invés de retornar o valor final definido ao parcelar a divida.

## Passos para reproduzir (para _bugs_)

1.Criar e parcelar a uma divida.
2.Após esperar a passagem de um ou mais dias usar a controller checkAmount,ela recalculará o valor da divida para a data atual apesar da mesma já ter sido parcelada.

**Comment by andrewlucasgs** [comment]
PR aceito e bug desfeito. Obrigado pela contribuição, e sinta-se a vontate para reportar qualquer bug que encontrar.
