### ISSUE TITLE
Colocar botão em torno de parcelar dívida e cancelar overdraft

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#186]
## Descrição da Mudança *

O modo link das funcionalidades de parcelar dívida e cancelar overdraft é ruim para a visualização, então essa issue é para transformar ambos em botão.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [ ] Tranformar Parcelar Dívida e Cancelar overdraft em botão

## Critérios de Aceitação * 

- [ ] Parcelar Dívida e Cancelar overdraft ser botão

**Comment by andrewlucasgs** [comment]
Resolvido na issue #187.
