### ISSUE TITLE
Modificar ícones, fontes e espaçamentos

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#187]
## Descrição da Mudança *

Refatorar os ícones, fontes e espaçamentos para manter uma melhor padronização.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [ ] Definir uma fonte que seja agradável para aplicativo mobile
- [ ] Modificar ícones colocando ícones de boa qualidade e mais adequados
- [ ] Colocar a mesma fonte definida anteriormente para todas as páginas
- [ ] Aplicar espaçamento padronizado entre  os componentes das telas
- [ ] Arrumar botões de "Parcelar Dívida" e "Cancelar Overdraft" para que fiquem com visual de botões.

## Critérios de Aceitação * 

- [x] Todas as páginas estarem com a nova fonte
- [x] Todos componentes e tamanhos serem padronizados
- [x] Espaçamento estar padronizado entre os componentes
- [x] Botões "Parcelar Dívida" e "Cancelar Overdraft" com layout de botão.

**Comment by ErickCReis** [comment]
Agora todo app tem um desing padrão, parabéns!
