### ISSUE TITLE
Atualizar saldo ao criar nova dívida

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#188]
## Descrição da Mudança *

O saldo não atualiza quando cria uma nova dívida.  Logo, essa issue se destina a fazer com que o saldo atualize após criar nova dívida.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [ ] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Resultado Esperado (para _bugs_)

Que o saldo seja atualizado assim que uma nova dívida for gerada. 

## Passos para reproduzir (para _bugs_)

1. Usar limite do cheque especial
2. Observar a criação da dívida e o comportamento do saldo.

**Comment by nahmrodrigues** [comment]
Essa issue provavelmente foi resolvida em uma das issues anteriores. Temos que testar para ver se o bug ainda está ocorrendo.

**Comment by nahmrodrigues** [comment]
O bug está sendo corrigido no método create do OverdraftDebtUtils, porém, continua sem correção no método create da controller do OverdraftDebt. Temos que ver qual método de fato está sendo utilizado.

**Comment by JongaMatos** [comment]
Este bug já foi resolvido em outra issue.
