### ISSUE TITLE
Restringir caracteres das operações de entrada e saída de recursos

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#189]
## Descrição da Mudança *

Não permitir que o usuário digite letras nas operações de cash in e cash out, apenas números.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Restringir caracteres dos campos de entrada da funcionalidade de cash in e cash out para números

## Critérios de Aceitação * 

- [x] Campos de entrada de cash in e cash out não aceitar letras

**Comment by ErickCReis** [comment]
Issue corrigida juntamente com a Issue #192 no PR #197 .
