### ISSUE TITLE
Traduzir e refatorar os textos apresentados no app

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#190]
## Descrição da Mudança *

Através do primeiro teste de usabilidade, constatou-se que alguns textos apresentados no aplicativo não são intuitivos ao usuário e alguns encontram-se em outro idioma. Essa issue destina-se a melhorar a apresentação dos textos e mensagens exibidas no aplicativo.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [ ] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Modificar o texto  'Usar cheque especial' para 'Acompanhar cheque especial'
- [x] Retirar qualquer referência ao termo "Crédito Especial"
- [x] Modificar todos os textos para que sejam intuitivos e se adequem às funcionalidades do aplicativo.
- [x] Traduzir todos os textos que estão em Inglês

## Critérios de Aceitação * 

- [ ] Textos estarem intuitivos
- [ ] Textos estarem em Português

**Comment by andrewlucasgs** [comment]
Textos e mensagens mais claras, e seguindo um padrão de linguagem e formatação. Tarefa concluída.
