### ISSUE TITLE
TS15 - Melhorar telas de Cash-In e Cash-Out

### ISSUE THREAD

**Issue by nahmrodrigues** [fga-eps-mds/2019.2-Over26#192]
## Descrição da Mudança *

Essa issue se destina às melhorias necessárias nas telas de cash-in e cash-out.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [ ] Esta issue tem uma boa definição de critérios de aceitação.
- [ ] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Mostrar mensagem de erro ao usuário que tenta fazer uma operação de cash-out, na condição em que o valor excede o limite disponível no cheque especial.
- [x] Padronizar o campo onde o usuário insere o valor na tela de cash-in com o da tela de cash-out.

## Critérios de Aceitação * 

- [x] A mensagem de erro quando o usuário tenta usar um valor maior do que seu limite do cheque especial deve estar aparecendo na tela.
- [x] O tipo a forma de apresentação do campo onde o usuário insere o valor na tela de cash-in deve ser igual ao da tela de cash-out.

**Comment by mlfaa** [comment]
@ErickCReis @LuizaCezario É importante que vocês restrinjam o campo de Valor somente para ser digitado números. Pois coloquei R$20,00 (com vírgula) e achei um bug, ele dá erro e por algum motivo apaga a conta do usuário.

**Comment by ErickCReis** [comment]
> @ErickCReis @LuizaCezario É importante que vocês restrinjam o campo de Valor somente para ser digitado números. Pois coloquei R$20,00 (com vírgula) e achei um bug, ele dá erro e por algum motivo apaga a conta do usuário.

Esse erro foi corrigido limitando os caracteres permitidos no campo de valor, e está incluso no PR #197
