### ISSUE TITLE
Consertar tela de parcelamento.

### ISSUE THREAD

**Issue by JongaMatos** [fga-eps-mds/2019.2-Over26#195]
## Critérios de Aceitação * 

- [x] Depois de parcelar a divida, não aparecer a opção de de parcelamento até outra divida ser criada.
- [x] Liberar o cheque especial após o parcelamento da divida.

## Resultado Esperado (para _bugs_)

Não ir para a tela de parcelamento se não houver divida não parcelada e liberar o cheque especial após o parcelamento da divida.

## Passos para reproduzir (para _bugs_)

1.Criar um cheque especial.
2.Usar o cheque especial.
3.Criar divida.
4.Parcelar divida.
5.Ao entrar na tela 'Usar cheque especial' aparecerá novamente a tela para parcelar a divida já parcelada (também não sera possível usar o cheque especial depois de criar a divida).

**Comment by andrewlucasgs** [comment]
PR aceito, obrigado por reportar e resolver o bug.
