### ISSUE TITLE
Aumentar a cobertura de testes - Backend

### ISSUE THREAD

**Issue by nahmrodrigues** [fga-eps-mds/2019.2-Over26#199]
## Descrição da Mudança *

Aumentar a cobertura de testes unitários no backend, para garantir um bom funcionamento dos métodos da API.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Testar classes com baixa cobertura de testes no backend
- [x] Aumentar a cobertura de testes

## Critérios de Aceitação * 

- [x] A cobertura de testes deve estar em, no mínimo, 90%.

**Comment by ErickCReis** [comment]
A cobertura do testes unitário passou para 92%, parabéns!
