### ISSUE TITLE
TS18 - Não é possível retirar um valor superior ao limite do cheque especial

### ISSUE THREAD

**Issue by ErickCReis** [fga-eps-mds/2019.2-Over26#203]
## Resultado Esperado (para _bugs_)

Deve ser possível fazer a retirada de um valor superior ao limite caso o usuário tenha o saldo suficiente.

## Passos para reproduzir (para _bugs_)

1. Ativar o cheque especial
2. Retirar qualquer valor acima de 200 reais, 250 por exemplo.

**Comment by andrewlucasgs** [comment]
PR aceito, bug resolvido. Agora é possível realizar retiradas maiores que o limite do cheque especial
