### ISSUE TITLE
Parcelamento sem definir data de vencimento

### ISSUE THREAD

**Issue by ErickCReis** [fga-eps-mds/2019.2-Over26#204]
## Resultado Esperado (para _bugs_)

Não deve ser possível fazer o parcelamento sem uma data estiver selecionada.

## Passos para reproduzir (para _bugs_)

1. Ativar o cheque especial
2. Utilizar o o cheque especial
3. Atualizar a data do cheque especial
4. Confirmar o parcelamento sem definir uma data

### Resultado
![image](https://user-images.githubusercontent.com/30873873/69470156-9d51b800-0d73-11ea-8901-909d23d57552.png)

**Comment by andrewlucasgs** [comment]
PR aceito, bom trabalho.
