### ISSUE TITLE
TS16 - Traduzir Cash In e Cash Out

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#208]
## Descrição da Mudança *

Traduzir os termos de Cash In e Cash Out no aplicativo.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Trocar Cash In por Depósito no aplicativo
- [x] Trocar Cash Out por Retirada no aplicativo

## Critérios de Aceitação * 

- [x] Os termos Cash in e Cash out estarem traduzidos

**Comment by ErickCReis** [comment]
Issue resolvida com o PR #207.
