### ISSUE TITLE
TS17 - Consultar dívida

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#209]
## Resultado Esperado (para _bugs_)

Mostrar o consultar dívida somente quando há uma dívida.

## Passos para reproduzir (para _bugs_)

1. Ativar o cheque especial 
2. Ir para a tela principal 
3. Estar mostrando consultar dívida mesmo sem ter uma

**Comment by ErickCReis** [comment]
Bug resolvido com o PR #212 .
