### ISSUE TITLE
Parcelar Dívida

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#211]
## Resultado Esperado (para _bugs_)

Ao parcelar uma dívida deve-se obter sucesso.

## Passos para reproduzir (para _bugs_)

1. Ativar cheque especial
2. Retirar R$110,00
3. Ajustar os dias
4. Parcelar dívida (Mensagem de Não é possível parcelar)
5. Quando consulta a dívida ela está parcelada e a Track Limit está travada

**Comment by andrewlucasgs** [comment]
PR aceito, fechando a issue, caso um novo bug seja encontrado, uma nova issue deve ser aberta
