### ISSUE TITLE
TS19 - Salvar o limite com valor inferior ao valor utilizado

### ISSUE THREAD

**Issue by ErickCReis** [fga-eps-mds/2019.2-Over26#215]
# Resultado Esperado (para _bugs_)

Não deve ser possível salvar um novo limite se este é inferior ao valor utilizado.
Uma aviso deve ser exibido.

## Passos para reproduzir (para _bugs_)

1. Ativar Cheque Especial
2. Retirar 200 reais
3. Na tela acompanhar ajustar o valor para 50 reais
4. Salvar

**Comment by andrewlucasgs** [comment]
PR aceito. Esse bug na hora de mudar o limite não existe mais.
