### ISSUE TITLE
TS20 - Melhorar UI do aplicativo

### ISSUE THREAD

**Issue by andrewlucasgs** [fga-eps-mds/2019.2-Over26#220]
## Descrição da Mudança *

Alterar a fonte e padronizar. Ajustar alguns bugs no layout e padronizar espaçamentos.

## Checklist *

- [ ] Esta issue tem um nome significativo.
- [ ] O nome da issue está no padrão.
- [ ] Esta issue tem uma descrição de fácil entendimento.
- [ ] Esta issue tem uma boa definição de critérios de aceitação.
- [ ] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [ ] Alterar fonte, para uma fonte mais user-friendly
- [ ] Ajustar tela de tracklimit de acordo com protóripo versão 1.
- [ ] Padronizar espaçamentos
- [ ] Corrigir erros de layout na main activity e no start activity

## Critérios de Aceitação * 

- [ ] App possuir um design mais user-friendly
- [ ] fontes de titulos, textos e labels padronizadas
- [ ] O app possuir uma identidade visual.

**Comment by JongaMatos** [comment]
PR aceito
