### ISSUE TITLE
US02 - Solicitar Crédito

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#30]
## Descrição da Mudança *

Eu, como usuário desejo solicitar a concessão de crédito para que eu possa realizar compras independente do meu saldo.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [ ] Fazer botão de solicitação que leva para página com formulário de solicitação 
- [ ] Fazer página de formulário com valor pretendido (campo de valorm já setado como valor máximo o valor indicado para clientes sem análise - a exemplo, o screenshot) , modo de uso do crédito (compras ou pagamento de dívidas ou investimentos - radiobutton simplificação das n telas de screenshot apresentadas) 
- [ ] Fazer botão enviar solicitação na página do formulário que grava a solicitação no banco de dados.
- [ ] Mostrar aviso de solicitação enviada para o usuário

## Critérios de Aceitação * 

- [ ] O layout das telas deve seguir o padrão da N26
- [ ] O botão de solicitação de crédito deve conter uma informação básica do que se trata, semelhante ao screenshot
- [ ] O formulário de solicitação deve ser intuitivo e conter os campos de valor e objetivo de uso. 
- [ ]  Após enviar a solicitação o usuário deve ser avisado do sucesso da ação

## Screenshots

Página de solicitação:

![image](https://user-images.githubusercontent.com/16694289/64858610-3f2f8880-d5fe-11e9-8d81-d3925f6158a3.png)

Pássos até o fornecimento do crédito:

![image](https://user-images.githubusercontent.com/16694289/64860909-f62f0280-d604-11e9-97b0-9a94d1bc59f1.png)

![image](https://user-images.githubusercontent.com/16694289/64860848-c8e25480-d604-11e9-9d20-5f041a599e0e.png)

![image](https://user-images.githubusercontent.com/16694289/64860951-12cb3a80-d605-11e9-9fcd-93cb6b294900.png)

Mais informações no vídeo : https://www.youtube.com/watch?v=YsKGkxq5n7I

**Comment by mlfaa** [comment]
Esta issue foi cancelada, pois foge ao escopo do projeto adotado para a disciplina. O escopo envolve somente o cheque especial.
