### ISSUE TITLE
US15 - Criar Perfil do Usuário - Backend

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#31]
## Descrição da Mudança *

Eu, como usuário desejo possuir um perfil no sistema para que eu possa manter restrição de acesso nas minhas atividades dentro da aplicação

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Criar um novo usuário com os campos: (cpf, name, email, phone, monthlyIncome, creditRequest)  (POST)
- [x] Alterar dados do usuário (UPDATE)
- [x] Visualizar dados do usuário (GET) 

Obs.: Os tipos das variáveis estão modelados no banco de dados. 

## Critérios de Aceitação * 

- [x] O backend para criação, alteração e visualização dos dados do usuário deve estar funcionando

**Comment by andrewlucasgs** [comment]
Pull request aceito, essa história foi concluída.
