### ISSUE TITLE
US04 - Checar Elegibilidade de Uso de Cheque Especial - Backend

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#32]
## Descrição da Mudança *

Eu, como usuário, desejo ativar ou desativar o crédito especial da minha conta, para que seja possível gerenciar meus gastos mensais.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Criar model para a entidade "Overdarft" com os atributos presentes no diagrama lógico
- [x] Criar controller para receber requisição, com método de checagem da elegibilidade, que automaticamente cria um Overdraft
- [x] Fazer requisição de POST no frontend, disparada quando o usuário clica no botão "Checar Elegibilidade"

## Critérios de Aceitação * 

- [x] A entidade Overdraft modelada
- [x] Ao clicar no botão de checar elegibilidade (Tela 1), o usuário deve ser redirecionado para a Tela 2 (se a a requisição for concluída com sucesso) e criar um Overdraft (POST)

## Screenshots

![](https://uploaddeimagens.com.br/images/002/327/083/full/Captura_de_tela_de_2019-09-06_22-28-32.png?1567821956)

**Comment by andrewlucasgs** [comment]
Testei aqui e consegui fazer a requisição POST, seguindo esse exemplo.
Acredito que esse seja o caminho.

https://fuel.gitbook.io/documentation/core/fuel#making-requests

**Comment by JongaMatos** [comment]
Gente,tava tentando fazer fazer a parte de o frontend disparar a requisição pro backend ,já criei o botão e to tendo dificuldade com a parte da requisição.Sempre que clico no botão ta dando este erro da imagem,já escrevi e reescrevi mas fica dando a mesma mensagem e a requisição nunca chega no back.

![Captura de tela de 2019-09-20 22-40-48](https://user-images.githubusercontent.com/54087048/65366399-af8b6a80-dbf9-11e9-96a8-098399be6556.png)

**Comment by andrewlucasgs** [comment]
![image](https://user-images.githubusercontent.com/22451668/65366480-ef9f1d00-dbfa-11e9-99d9-adfebd64c103.png)

Adicionar isso ao manifest:
<uses-permission android:name="android.permission.INTERNET"/>

**Comment by JongaMatos** [comment]
Valeu,ta funcionando aqui.

**Comment by mlfaa** [comment]
https://github.com/fga-eps-mds/2019.2-Over26/pull/51
