### ISSUE TITLE
US16 - Manter conta de pagamento - Backend

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#38]
## Descrição da Mudança *

Eu, como usuário desejo possuir uma conta de pagamento para que eu possa  ter acesso às funcionalidades dentro da aplicação que necessitam de conta.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Criar uma conta de pagamento tabela classe Account com os seguintes atributos: user, agency, balance, number, transactions.  (POST)
- [x] Alterar dados da conta de pagamento (UPDATE)
- [x] Visualizar dados da conta de pagamento (GET) 
- [ ] Testes unitários

Obs.: Os tipos das variáveis estão modelados no banco de dados. 

## Critérios de Aceitação * 

- [ ] Deve ser possível criar conta de pagamento no Backend
- [ ] Deve ser possível alterar conta de pagamento no Backend
- [ ] Deve ser possível visualizar dados da conta de pagamento no Backend

**Comment by ErickCReis** [comment]
![Captura de tela de 2019-09-20 23-56-37](https://user-images.githubusercontent.com/30873873/65367063-5d9b1280-dc02-11e9-8cfc-a7922c8d353f.png)
Montamos a tabela e a classe Account seguindo o modelo, mas não estamos conseguindo acessar/modificar o banco de dados.

**Comment by andrewlucasgs** [comment]
Isso provavelmente é problema com a definição das suas rotas, já que está dando 404 Not Found.
Confira se está correto o caminho do POST /api/accounts

**Comment by ErickCReis** [comment]
Realmente estava faltando o 's', mas o problema continua, status '500 Internal Server Error' agora.

**Comment by ErickCReis** [comment]
Erro corrigido em [https://github.com/fga-eps-mds/2019.2-Grupo2-Backend/commit/d65fd469fd5ce0f6aef42e580e3075a70219c4c3](url)
