### ISSUE TITLE
US02 - Interface Cash-in

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#40]
## Descrição da Mudança *

Eu como usuário desejo inserir dinheiro na minha conta por meio de boleto ou transferência para que eu possa realizar transações financeiras. 
Essa funcionalidade será feita apenas no BackEnd, assim, a interface será apresentada ao usuário a partir do browser.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Criar página com formulário de Cash In (Valor, NumConta, remetente, forma, data)
- [x] Mensagem de sucesso após a transação ser realizada . "Seu depósito foi feito com sucesso"
- [x]  Ao submeter o formulário o saldo da conta deve ser atualizado

## Critérios de Aceitação * 

- [x] O saldo da conta deve ser atualizado

**Comment by Coredoisquad** [comment]
Procurei bastante no código e pesquisei para tentar achar o que podia ser, mas realmente não consegui entender
