### ISSUE TITLE
US17 - Parcelar a dívida após os 26 dias - Back

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#43]
## Descrição da Mudança *

Eu, como usuário desejo poder parcelar a minha dívida de crédito especial após o período de 26 dias, para que haja um impacto menor na minha renda mensal .

Essa issue diz respeito apenas ao backend da US17.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Fazer método de verificação de período de isenção, retornando 'false' apenas se a data atual menos a data do primeiro uso do cheque especial for maior que 26
- [x] Fazer método de criação da dívida, recebendo como parâmetro o id do usuário
- [x]  Fornecer ao front um método de consulta do valor total da dívida com os juros
- [x]  Fornecer ao front um método de consulta das opções de parcelamento (Número de parcelas, valor delas e data de vencimento)
- [ ]  Criar método para efetivar o parcelamento da dívida (POST), persistindo as informações de : Número de parcelas, Valor das parcelas, Data de pagamento das parcelas
- [ ] Testes unitários

## Critérios de Aceitação * 

- [ ] Testes com 90% de cobertura
- [ ] O método de criação da dívida deve recuperar o overdraft associado ao usuário e preencher os atributos da dívida com as informações do overdraft, obs: a data de entrada da dívida é igual à data do primeiro uso do cheque especial mais 26 dias
- [ ] O total da dívida deve ser calculado com base no limite usado pelo usuário do cheque especial (amount) mais os juros
- [ ] Os juros devem ser calculados levando em consideração a quantidade de dias entre a data atual e a data de entrada na dívida
- [ ]  Funções para parcelamento da dívida disponíveis para uso do front

**Comment by JongaMatos** [comment]
Eu tava tentando fazer um método que verifica se já se passaram os 26 dias,mas ele nunca ta retornando nada, percebi o mesmo problema no método getByPK,segue abaixo print do método e do terminal.
O que eu fiz errado??
![Captura de tela de 2019-09-26 12-34-23](https://user-images.githubusercontent.com/54087048/65702983-5472d100-e05a-11e9-8831-c9fbdce42cdb.png)
![Captura de tela de 2019-09-26 12-36-04](https://user-images.githubusercontent.com/54087048/65702995-589eee80-e05a-11e9-8838-3c25b01e63fe.png)

**Comment by JongaMatos** [comment]
Ja resolvi, tinha q trocar o return false por return res.status(200).send(false)
 e o return true por return res.status(200).send(true),e trocar o else de lugar (estava no if errado)

**Comment by andrewlucasgs** [comment]
Pull request aceito e merged na master.
