### ISSUE TITLE
US14 - Acompanhar dívida - Back 

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#45]
## Descrição da Mudança *

Eu, como usuário desejo acompanhar o valor da minha dívida, para que eu possa controlar os meus gastos.

Essa issue compreenderá apenas o backend da história.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x]  Fornecer ao front um método de consulta das parcelas de UMA dívida do usuário, recebendo como parâmetro o id da divida e retornando uma lista de parcelas da dívida, com os seguintes campos para cada pacela: status, valor, data de vencimento
- [x] Fazer testes unitários

## Critérios de Aceitação * 

- [x] Testes com 70% de cobertura
- [x]  Método de consulta das parcelas da dívida feito, retornando as parcelas associadas àquela dívida.

**Comment by nahmrodrigues** [comment]
A issue foi resolvida com o PR: https://github.com/fga-eps-mds/2019.2-Over26-Backend/pull/23
