### ISSUE TITLE
Fazer apresentação

### ISSUE THREAD

**Issue by nahmrodrigues** [fga-eps-mds/2019.2-Over26#80]
## Descrição da Mudança *

Elaborar e ensaiar apresentação do projeto na R1.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Fazer slides
- [x]  Definir roteiro da apresentação

## Critérios de Aceitação * 

- [x] Os slides devem estar feitos e revisados por todos
- [x] O roteiro deve estar definido (com quem vai apresentar o quê e em que ordem)

**Comment by mlfaa** [comment]
https://docs.google.com/presentation/d/1E-jeXzOZuKrFOzGHDhsqSe0rQkGMUxveZFeMevJJnS0/edit?usp=sharing
