### ISSUE TITLE
TS01 - Refatorar as controllers - Backend

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#92]
## Descrição da Mudança *

É necessário refatorar as controllers no Backend. 

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] É necessário deixar nas controllers somente o que for controller
- [x] As demais funções devem estar em um arquivo separado de utils

## Critérios de Aceitação * 

- [x] As funções devem estar funcionando corretamente 
- [x] As controllers devem estar funcionando corretamente 
- [x] O que for função deve estar no arquivo util 
- [x] O que for controller deve estar no arquivo de controllers
- [x] Os testes existentes devem estar passando

**Comment by nahmrodrigues** [comment]
A issue foi resolvida no PR: https://github.com/fga-eps-mds/2019.2-Over26-Backend/pull/17
