### ISSUE TITLE
TS03 - Refatorar as Models - Backend

### ISSUE THREAD

**Issue by ErickCReis** [fga-eps-mds/2019.2-Over26#94]
## Descrição da Mudança *

Adequar as models ao diagrama lógico atualizado.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Adicionar atributos "isActive" e "isBlocked" à classe Overdraft
- [x] Corrigir chaves primárias e estrangeiras
- [x] Adicionar restrições "allowNull" e "unique" à atributos que se encaixem nesses parâmetros 

## Critérios de Aceitação * 

- [x] As models devem estar de acordo com o diagrama lógico
- [x] As chaves primárias e estrangeiras devem estar funcionando

**Comment by ErickCReis** [comment]
Ainda não consegui encontrar uma forma de implementar as chaves estrangeiras compostas.

**Comment by nahmrodrigues** [comment]
A issue foi resolvida no PR: https://github.com/fga-eps-mds/2019.2-Over26-Backend/pull/17
