### ISSUE TITLE
TS04 - Corrigir requisição de parcelamento - Frontend

### ISSUE THREAD

**Issue by mlfaa** [fga-eps-mds/2019.2-Over26#97]
## Descrição da Mudança *

Corrigir requisição de criação das parcelas no Frontend.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [x] Esta issue está associada à uma milestone.
- [x] Esta issue tem uma pontuação estimada.

## Tarefas *

- [x] Fazer requisição de POST no back salvando as informações da opção de parcelamento escolhida pelo usuário no botão de salvar

## Critérios de Aceitação * 

- [x] Ao clicar em parcelar, deve ser criado os parcelamentos associados a dívida no backend

**Comment by ErickCReis** [comment]
Correção adicionada ao PR #88.
